### ISSUE TITLE
browserify-vanilla example does not work

### ISSUE THREAD

**Issue by monzonj** [sogko/gulp-recipes#10]
Hello
Using these modules versions the given example does not work. 

```
$ node -v
v0.12.2

$ npm -v
2.12.1

gulp": "^3.9.0",
"browserify": "^10.2.4",
"vinyl-transform": "^1.0.0"
```

```
gulp browserify
[16:43:03] Using gulpfile ~/Documents/workspace/test/gulpfile.js
[16:43:03] Starting 'browserify'...
_stream_readable.js:540
    var ret = dest.write(chunk);
                   ^
TypeError: undefined is not a function
    at Producer.ondata (_stream_readable.js:540:20)
    at Producer.emit (events.js:107:17)
    at Producer.Readable.read (_stream_readable.js:373:10)
    at flow (_stream_readable.js:750:26)
    at resume_ (_stream_readable.js:730:3)
    at _stream_readable.js:717:7
    at process._tickCallback (node.js:355:11) 
```

**Comment by monzonj** [comment]
Reason is that browserify.bundle() has changed in later versions.

Solution here: https://github.com/substack/node-browserify/issues/1198
